import regex as re

var_type = {0: "Core", 1: "Input"}

defn_type = {
    1: "Formula", 2: "Constant", 3: "Global", 4: "Parameter", 5: "Model Point", 6: "Generic Table",
    7: "Mortality Table", 8: "Year Dependent Mortality Table", 9: "Year Index Table", 10: "Time Index Values",
    11: "Extended Formula", 12: "t-Dependent Extended Formula", 13: "Module Link", 14: "Module Input",
    15: "Extended Module Input"
}

operators = [
    '^', '*', '/', '+', '-', '=', '<>', '<', '>', '<=', '>=', ':='  # standard / extended formulas
    '!=', '!', '&&', '||'  # standard formulas
]

read_params = ['D', 'G', 'N', 'P', 'R', 'S', 'U', 'Y', 'Z']

keywords = [
    'AND', 'AS',
    'BOOLEAN',
    'CASE', 'CHAR', 'CONSTRAINT',
    'DO', 'DYNAMIC_PERSISTENT',
    'EACH', 'ELSE', 'ELSEIF', 'ENDIF', 'ENDSWITCH', 'EQ',
    'FALSE', 'FOR',
    'GE', 'GT',
    'IF', 'INTEGER',
    'LE', 'LOOP', 'LT',
    'NE', 'NESTED_PERIOD', 'NEXT', 'NOT', 'NUMBER',
    'OPTION', 'OR',
    'PARAMETER', 'PERSISTENT', 'PRIVATE', 'PUBLIC',
    'QUIT', 'QUITLOOP',
    'REAL',
    'STAT_LIST', 'STEP', 'SWITCH',
    'TEXT', 'THEN', 'TO', 'TRUE',
    'VARIABLE_CONSTRAINT',
    'WHILE'
]

builtin_functions = [
    'ABS',
    'ACOS',
    'ACOSH',
    'AGG_PROJ_RESULT',
    'ARRAY_INITIALISE',
    'ARRAY_LBOUND',
    'ARRAY_MAX',
    'ARRAY_MIN',
    'ARRAY_PROD',
    'ARRAY_SIZE',
    'ARRAY_SUM',
    'ARRAY_UBOUND',
    'ASIN',
    'ASINH',
    'ATAN',
    'ATAN2',
    'ATANH',
    'BEM',
    'BLACK_SCH',
    'BUY_ASSET',
    'CALC_LOOP',
    'CALL_DLL',
    'COM_YEAR_END',
    'COS',
    'COSH',
    'CPU_ARCHITECTURE',
    'CTE_CALC',
    'CUMULATIVE_BIVARIATE_NORMAL',
    'CUMULATIVE_NORMAL',
    'CURR_DYN_START_T',
    'CURRENT_START_MONTH',
    'CURRENT_START_YEAR',
    'DIV',
    'DYN_PROJ_PERIOD',
    'DYNAMIC_PERIOD',
    'DYNAMIC_RUN',
    'ENUM_SIZE',
    'ENUM_TO_INT',
    'ENUM_TO_TEXT',
    'ERROR',
    'EXP',
    'FIND_FORWARD',
    'FIND_REVERSE',
    'FIRST_CALC',
    'FIRST_MODEL_POINT',
    'FIRST_MODEL_POINT_ONLY',
    'FRACT',
    'FUT_ACCUM_Y',
    'GAUSS_JORDAN_SOLVE',
    'GROUP_AFTER',
    'IGNORE_MODEL_POINT',
    'IMD_PRODUCT',
    'IMS_PRODUCT',
    'IN_FIRST_MAIN_LOOP',
    'IN_LAST_MAIN_LOOP',
    'IN_LOOP_AT_END',
    'IN_LOOP_AT_START',
    'IN_MEMORY_START_T',
    'IN_NESTED_PERIOD',
    'INCLUDING_NEW_BUS_INACCUMS',
    'INT',
    'INT_TO_ENUM',
    'INTERP',
    'INV_CUMULATIVE_NORMAL',
    'IRR',
    'ITERATION',
    'JUST_VAR_NAME',
    'LAST_MODEL_POINT',
    'LAST_SPCODE_FOR_EXISTING_BUS',
    'LAST_SPCODE_FOR_NB_BASED_ON_SALES',
    'LEFT',
    'LENGTH',
    'LEVEL_NUMBER',
    'LIBRARY',
    'LN',
    'LOG',
    'LOOP_AT_END',
    'LOOP_AT_START',
    'MAX',
    'MAXT',
    'MIN',
    'MINT',
    'MOD',
    'MOD_POINT_NO',
    'MODULE_LINK_CONDITION',
    'MODULE_LINK_NAME',
    'MODULE_NAME',
    'MONINT',
    'MORT_MAX_AGE',
    'MORT_MIN_AGE',
    'MORT_RATE',
    'MORT_SELECT_PERIOD',
    'MULT',
    'NESTED_DEPTH',
    'NESTED_RUN',
    'NESTED_SCENARIO',
    'NESTED_SIMULATION',
    'NESTED_START_MONTH',
    'NESTED_START_YEAR',
    'NEW_BUS_IN_ACCUMS',
    'NEW_BUSINESS_METHOD',
    'NO_CALC',
    'NUM_TO_TEXT',
    'ORIGINAL_SPCODE',
    'PAST_ACCUM_Y',
    'PI',
    'PRINT',
    'PRINT_TO_FILE',
    'PROD',
    'PROD_NAME',
    'PROJ_RESULT',
    'PROP_BUY_ASSET',
    'RAND_BETA',
    'RAND_LOGNORMAL',
    'RAND_NORMAL',
    'RAND_NUMBER',
    'RAND_POISSON',
    'RAND_SAMPLE',
    'RAND_UNIFORM',
    'READ_AIDS_TABLE',
    'READ_FLEXIBLE_TABLE',
    'READ_GENERIC_TABLE',
    'READ_GENERIC_TABLE_TEXT',
    'READ_GLOBAL',
    'READ_GLOBAL_TEXT',
    'READ_MODEL_POINT',
    'READ_MODEL_POINT_TEXT',
    'READ_MORT_TABLE',
    'READ_NESTED_STAT',
    'READ_NESTED_STAT_ALIAS',
    'READ_NESTED_STOCH_TABLE',
    'READ_PARAMETER',
    'READ_PARAMETER_TEXT',
    'READ_PREVIOUS_DYN_LOOP',
    'READ_RESULTS',
    'READ_STOCH_TABLE',
    'READ_TABLE_NAME',
    'READ_TABLE_ROW',
    'READ_TABLE_ROW_TEXT',
    'READ_YEAR_DEP_MORT_TABLE',
    'READ_YEAR_INDEX_TABLE',
    'REPEAT_COUNT',
    'REPEAT_LEVEL',
    'RESULTS_LOCATION',
    'RIGHT',
    'ROUND',
    'ROUND_DOWN',
    'ROUND_NEAR',
    'ROUND_UP',
    'RUN_IDENT',
    'RUN_NUMBER',
    'SAME_AS_PROD_NAME',
    'SCENARIO_SELECTED',
    'SELL_ASSET',
    'SET_DYNAMIC_PERIOD',
    'SET_DYNAMIC_PROJ_PERIOD',
    'SIMULATION',
    'SIN',
    'SINH',
    'SPCODE',
    'START_MONTH',
    'START_YEAR',
    'STOCH_RESULT',
    'STRONG_T_LIMIT',
    'SUBSTR',
    'SUM',
    'TABLE_COLUMNS',
    'TABLE_ROWS',
    'TAN',
    'TANH',
    'TERMINATE',
    'TEXT_TO_ENUM',
    'TEXT_TO_NUM',
    'VALN_DAY',
    'VALN_MONTH',
    'VALN_YEAR',
    'VAR_NAME',
    'WARNING',
    'WORKSPACE',
    'YD_MORT_MAX_AGE',
    'YD_MORT_MAX_YEAR',
    'YD_MORT_MIN_AGE',
    'YD_MORT_MIN_YEAR',
    'YD_MORT_RATE'
]

valid_var_regex = re.compile(
    R'(?!\b' + R'\b|\b'.join([*keywords, *builtin_functions]) + R'\b)' +  # ignore reserved tokens
    R'(?<!;.*)' +  # ignore comments
    R'(?<!")\b([a-zA-Z][a-zA-Z0-9_]{0,35})\b(?!")'  # variable names
)
